name = "doc-zudo-panel-designer"
main = "./dist/_worker.js"
compatibility_date = "2026-07-17"
compatibility_flags = ["nodejs_compat"]

workers_dev = false
preview_urls = false

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "404-page"

[env.preview]
workers_dev = false
preview_urls = true

[env.production]
workers_dev = false
preview_urls = false

[[env.production.routes]]
pattern = "doc-zudo-panel-designer.takazudomodular.com"
custom_domain = true
