// Raster-trace SVG -> vector PathLayers. Pure (no canvas/DOM), so it is
// directly unit-testable against fixture SVG strings — the actual
// @image-tracer-ts call lives in trace-pipeline.ts.
//
// The <svg>/<path> parsing is a couple of regexes rather than a real XML
// parser: the input is machine-generated by @image-tracer-ts (never
// arbitrary/user-authored markup), and its output shape is narrow (one <svg>
// tag, flat <path fill="..." d="..." /> children).
import { SVGPathData } from 'svg-pathdata';
import { mintId, PALETTE, type ColorIndex, type PathLayer, type PathPoint, type Pt } from '@zpd/core';
import { nearestPaletteIndex } from './nearest-palette-color';

// Caps runaway trace results (a busy source image can produce thousands of
// tiny color regions) at a layer count the editor stays usable with.
const MAX_TRACE_LAYERS = 300;

export interface TraceTarget {
  x: number;
  y: number;
  width: number;
  height: number;
}

interface SubPath {
  points: PathPoint[];
  closed: boolean;
}

// Normalizes one <path>'s `d` into MOVE_TO/LINE_TO/CURVE_TO/CLOSE_PATH
// commands, then groups them into subpaths split at each MOVE_TO.
function commandsToSubPaths(d: string): SubPath[] {
  // normalizeHVZ(false) is required: the default rewrites a Z close-path into
  // a plain line back to the start point and drops the CLOSE_PATH command
  // entirely, so every traced region would silently become an open path.
  const data = new SVGPathData(d).toAbs().aToC().normalizeST().qtToC().normalizeHVZ(false);
  const subPaths: SubPath[] = [];
  let current: SubPath | null = null;
  for (const cmd of data.commands) {
    if (cmd.type === SVGPathData.MOVE_TO) {
      current = { points: [{ x: cmd.x, y: cmd.y }], closed: false };
      subPaths.push(current);
    } else if (!current) {
      continue;
    } else if (cmd.type === SVGPathData.LINE_TO) {
      current.points.push({ x: cmd.x, y: cmd.y });
    } else if (cmd.type === SVGPathData.CURVE_TO) {
      const prev = current.points[current.points.length - 1];
      prev.hout = { x: cmd.x1, y: cmd.y1 };
      current.points.push({ x: cmd.x, y: cmd.y, hin: { x: cmd.x2, y: cmd.y2 } });
    } else if (cmd.type === SVGPathData.CLOSE_PATH) {
      current.closed = true;
      // drop a duplicated closing anchor when the tracer also emitted an
      // explicit line back to the start point right before Z
      const first = current.points[0];
      const last = current.points[current.points.length - 1];
      if (
        current.points.length > 1 &&
        Math.abs(first.x - last.x) < 1e-6 &&
        Math.abs(first.y - last.y) < 1e-6
      ) {
        if (last.hin) first.hin = last.hin;
        current.points.pop();
      }
    }
  }
  return subPaths.filter((sp) => sp.points.length >= 2);
}

// @image-tracer-ts defaults to viewBox-only output (no width/height attrs on
// <svg>) — width/height wins when both are present, viewBox is the fallback.
function svgSourceDims(svg: string): { width: number; height: number } {
  const svgTag = svg.match(/<svg[^>]*>/)?.[0] ?? '';
  const widthMatch = svgTag.match(/\swidth="([\d.]+)/);
  const heightMatch = svgTag.match(/\sheight="([\d.]+)/);
  const viewBoxMatch = svgTag.match(/viewBox="[\d.\s-]*?([\d.]+)\s+([\d.]+)"/);
  const width = Number(widthMatch?.[1] ?? viewBoxMatch?.[1] ?? 0) || 1;
  const height = Number(heightMatch?.[1] ?? viewBoxMatch?.[2] ?? 0) || 1;
  return { width, height };
}

// Parses a traced SVG into one PathLayer per color region, scaled from
// source-SVG space into `target`'s mm rect (the source image layer's bbox).
export function svgToPathLayers(svg: string, target: TraceTarget): PathLayer[] {
  const { width: svgW, height: svgH } = svgSourceDims(svg);
  const sx = target.width / svgW;
  const sy = target.height / svgH;
  const scale = (p: Pt): Pt => ({ x: target.x + p.x * sx, y: target.y + p.y * sy });
  const scalePoints = (points: PathPoint[]): PathPoint[] =>
    points.map((p) => ({
      ...scale(p),
      ...(p.hin ? { hin: scale(p.hin) } : {}),
      ...(p.hout ? { hout: scale(p.hout) } : {}),
    }));

  const paletteHexes = PALETTE.map((entry) => entry.hex);
  const layers: PathLayer[] = [];
  const pathTags = svg.match(/<path\s[^>]*?\/?>/g) ?? [];
  let n = 0;
  for (const tag of pathTags) {
    const dMatch = tag.match(/\sd="([^"]+)"/);
    if (!dMatch) continue;
    const fillMatch = tag.match(/\sfill="([^"]+)"/);
    const fillIndex = fillMatch ? nearestPaletteIndex(fillMatch[1], paletteHexes) : null;
    if (fillIndex === null) continue;

    // one layer per traced color region; a region's compound subpaths
    // (outer boundary + hole/island contours) stay together on that layer so
    // evenodd fill (see renderer.ts) keeps holes as holes
    const subs = commandsToSubPaths(dMatch[1]);
    if (subs.length === 0) continue;
    n += 1;
    layers.push({
      id: mintId('trace'),
      name: `trace-${n}`,
      type: 'path',
      points: scalePoints(subs[0].points),
      ...(subs.length > 1
        ? { extraSubpaths: subs.slice(1).map((s) => scalePoints(s.points)) }
        : {}),
      closed: true,
      fill: fillIndex as ColorIndex,
      stroke: null,
      strokeWidth: 0,
    });
    if (layers.length >= MAX_TRACE_LAYERS) break;
  }
  return layers;
}
